dist: xenial  # required for Python >= 3.7
language: python

python:
  - "2.7"
  - "3.7"

install:
  - pip install -r requirements.txt -U
  - python install-testplan-ui --verbose --dev

script:
  - ./scripts/utils/crlf_check.sh
  - ./scripts/utils/black_check.py
  - pylint --rcfile pylintrc testplan
  - pytest tests --verbose

